servingCACertificate: gatekeeper-webhook-tls
mutations:
  # proxy settings
  podProxySettings:
    noProxy:
    httpProxy:
    httpsProxy:
  # apply mutations on objects whose labels match namespace labels
  namespaceSelectorForProxy: {}
  # disable the following namespaces
  excludeNamespacesFromProxy: []
# Adds a namespace selector to the validation controller webhook
admissionControllerNamespaceSelector:
  matchExpressions: []
# Adds an object selector to the validation controller webhook
admissionControllerObjectSelector:
  matchExpressions: []
  # - {key: foo, operator: NotIn, values: ["bar"]}
  matchLabels: []
  # - foo: bar

# Copied from gatekeeper values
replicas: 3
disableMutation: false
disableValidatingWebhook: false
validatingWebhookTimeoutSeconds: 3
validatingWebhookFailurePolicy: Ignore
validatingWebhookCheckIgnoreFailurePolicy: Fail
enableDeleteOperations: false
enableExternalData: false
mutatingWebhookFailurePolicy: Ignore
mutatingWebhookTimeoutSeconds: 3
logLevel: INFO
logDenies: false
emitAdmissionEvents: false
image:
  repository: openpolicyagent/gatekeeper
  crdRepository: openpolicyagent/gatekeeper-crds
  release: v3.7.0
  pullPolicy: IfNotPresent
  pullSecrets: []
podAnnotations:
  { container.seccomp.security.alpha.kubernetes.io/manager: runtime/default }
podLabels: {}
controllerManager:
  exemptNamespaces: []
  exemptNamespacePrefixes: []
  hostNetwork: false
  dnsPolicy: Default
  port: 8443
  metricsPort: 8888
  healthPort: 9090
  priorityClassName: system-cluster-critical
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: gatekeeper.sh/operation
                  operator: In
                  values:
                    - webhook
            topologyKey: kubernetes.io/hostname
          weight: 100
  tolerations: []
  nodeSelector: { kubernetes.io/os: linux }
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
service: {}
disabledBuiltins:
