apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dkp-insights-management
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: dkp-insights-management
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-dkp-insights-charts-management
        namespace: kommander-flux
      version: v0.10.0-rc1
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: dkp-insights-management-0.10.0-d2iq-defaults
  releaseName: dkp-insights-management
  targetNamespace: ${releaseNamespace}
