---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kommander-common
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kommander-common
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-kommander-charts
        namespace: kommander-flux
      version: "${kommanderChartVersion:=v2.3.0-dev}"
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: kommander-common
  valuesFrom:
    - kind: ConfigMap
      name: kommander-common-0.1.0-d2iq-defaults
