{{- if not .Values.disableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kommander-ca
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
  name: gatekeeper-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/admit
  failurePolicy: {{ .Values.validatingWebhookFailurePolicy }}
  matchPolicy: Exact
  name: validation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
    - key: app.kubernetes.io/part-of
      operator: NotIn
      values:
        - flux
    {{- with .Values.admissionControllerNamespaceSelector.matchExpressions }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  objectSelector:
    {{- with .Values.admissionControllerObjectSelector.matchExpressions }}
    matchExpressions:
    {{ toYaml . | nindent 4 }}
    {{ end }}
    {{- with .Values.admissionControllerObjectSelector.matchLabels }}
    matchLabels:
    {{ toYaml . | nindent 4 }}
    {{ end }}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    {{- if .Values.enableDeleteOperations }}
    - DELETE
    {{- end}}
    resources:
    - '*'
  sideEffects: None
  timeoutSeconds: {{ .Values.validatingWebhookTimeoutSeconds }}
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/admitlabel
  failurePolicy: {{ .Values.validatingWebhookCheckIgnoreFailurePolicy }}
  matchPolicy: Exact
  name: check-ignore-label.gatekeeper.sh
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
  sideEffects: None
  timeoutSeconds: {{ .Values.validatingWebhookTimeoutSeconds }}
{{- end }}
