---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kommander-root-ca
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: false
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  path: ./services/root-ca/0.0.1/root-ca
  timeout: 60s
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}

