---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: open-policy-agent.github.io-charts
        namespace: kommander-flux
      version: 3.7.0
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: kommander-gatekeeper
  valuesFrom:
    - kind: ConfigMap
      name: gatekeeper-3.7.0-d2iq-defaults
    - kind: ConfigMap
      name: gatekeeper-overrides
      optional: true
  values:
    disableMutation: true
    disableValidatingWebhook: true
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: v1
            kind: Service
            metadata:
              name: gatekeeper-webhook-service
              namespace: ${releaseNamespace}
            spec:
              selector:
                release: gatekeeper-setup
          - $patch: delete
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: gatekeeper-controller-manager
              namespace: ${releaseNamespace}
          - $patch: delete
            apiVersion: v1
            kind: Secret
            metadata:
              name: gatekeeper-webhook-server-cert
              namespace: ${releaseNamespace}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper-setup
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: gatekeeper
  chart:
    spec:
      chart: charts/gatekeeper-setup
      sourceRef:
        kind: GitRepository
        name: management
        namespace: kommander-flux
      version: "v0.0.1"
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: gatekeeper-setup
  valuesFrom:
    - kind: ConfigMap
      name: gatekeeper-3.7.0-d2iq-defaults
    - kind: ConfigMap
      name: gatekeeper-overrides
      optional: true
